### ISSUE TITLE
What's the problem.

### ISSUE THREAD

**Issue by letmejustdoit** [hisxo/JSpector#2]
![image](https://user-images.githubusercontent.com/33480884/229024593-606e073e-0dfd-4810-aa3b-ab48b93fae1f.png)
![image](https://user-images.githubusercontent.com/33480884/229024727-cb8bab30-aed4-452b-a88e-2e2c5361e646.png)

Your software cannot analyze JS files and does not receive feedback，What's the problem

**Comment by letmejustdoit** [comment]
After the software scan, there were no results.

**Comment by hisxo** [comment]
Hi @letmejustdoit,

Have you defined a scope like **tesla.com** on _Scope settings_? It's mandatory for JSpector :)

Cheers
